#!/bin/bash

cd chempotpy

for system in ALC AlmHn Aln ArNO BrH2 BrHCl C2H2N2O C2H2O C2H6Cl C2H6F C2H6H C2H6O C2H6OH C2H7 C2N C3H7NO C6H5SH C6H6O C7H8S CH2O CH2O2 CH3NH2 CH3OH CH4 CH4Br CH4Cl CH4CN CH4F CH4_H2O_H2O CH4O CH4OCl CH4OF CH4OH CH5 CH5O2 CH5p Cl2H ClH2 ClH2O ClNH3 COCO F2H F2H2 FH2 FH2O GeH4OH GeH5 H2CO H2O2 H2OBr H3 H3Cl H3ClO H3p H3S H4O2 HClOH HO3 HOBr HOCO_Ar I2H IH2 K2Rb2 LiFH MCH MXH N2HOCp N2O N2O2 N3 N4 NaFH NaH2 NH3 NH3CN NH3OH NH4 NO2 O2H O2H3 O3 O4 OH2 OH3 SiH4Cl SiH5 SiOH YRH
do

cd ${system}
rm *.so

  for surface in *.f
  do
  if [ -f "$surface" ]; then
    name=`echo $surface | sed 's/\.[^\.]*$//'`
    f2py3 -c -m ${name} --f77flags="-fallow-argument-mismatch -std=legacy" ${surface} > ${name}.log
  fi
  done

  for surface in *.f90
  do
  if [ -f "$surface" ]; then
    name=`echo $surface | sed 's/\.[^\.]*$//'`
    f2py3 -c -m ${name} --f90flags="-fallow-argument-mismatch -std=legacy" ${surface} > ${name}.log
  fi
  done

cd ..
done


echo "=========================================================================="
echo "=========================================================================="
echo "   "
echo "chempotpy compilation has been finished, now check if they are successful"
echo "   "
echo "=========================================================================="
echo "=========================================================================="

